defaults:
  - config
  - data: narrativeqa
  - _self_

run_name: sim
overwrite: True
log_level: WARNING

data:
  interleave: True
  max_seq_len: 128000
  max_rows: 50000

strategies:
  no_cache: {}
  log: {}
  sqrt: {}
  # Block
  block_2048: {_base_: block, block_size: 2048}
  block_4096: {_base_: block, block_size: 4096}
  block_8192: {_base_: block, block_size: 8192}
  block_16384: {_base_: block, block_size: 16384}
 # Balanced
  balanced_1:  {_base_: balanced, n_blocks: 1}
  balanced_2:  {_base_: balanced, n_blocks: 2}
  balanced_3:  {_base_: balanced, n_blocks: 3}
  balanced_5:  {_base_: balanced, n_blocks: 5}
  balanced_8:  {_base_: balanced, n_blocks: 8}
  balanced_12: {_base_: balanced, n_blocks: 12}
  balanced_16: {_base_: balanced, n_blocks: 16}
  balanced_30: {_base_: balanced, n_blocks: 30}
  # D-optimal
  dp_1:  {_base_: hist_exp_decay, n_blocks: 1}
  dp_2:  {_base_: hist_exp_decay, n_blocks: 2}
  dp_3:  {_base_: hist_exp_decay, n_blocks: 3}
  dp_5:  {_base_: hist_exp_decay, n_blocks: 5}
  dp_8:  {_base_: hist_exp_decay, n_blocks: 8}
  dp_12: {_base_: hist_exp_decay, n_blocks: 12}
  dp_16: {_base_: hist_exp_decay, n_blocks: 16}
  dp_30: {_base_: hist_exp_decay, n_blocks: 30}

plot_results:
 _target_: plot_results.plot_all
 break_at: 35

cache_manager:
  _target_: spase_cache.utils.FixedSizeCache
  max_cached_sequences: 100


benchmark_e2e:
  dry_run: true
